# Generated by Django 2.2.1 on 2019-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('county_id', models.PositiveSmallIntegerField()),
                ('city_id', models.PositiveIntegerField()),
                ('type_id', models.PositiveSmallIntegerField()),
                ('vehicle_type', models.PositiveSmallIntegerField()),
                ('duration_id', models.PositiveSmallIntegerField()),
                ('available_seats', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tours',
            },
        ),
    ]
