# Generated by Django 2.2.1 on 2019-06-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tours',
            table=None,
        ),
    ]
