# Generated by Django 2.2.1 on 2019-06-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20190601_0926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tours',
            table='tours',
        ),
    ]
